# Generated by Django 4.2 on 2025-01-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='account',
            name='qr_code',
            field=models.ImageField(null=True, upload_to='users-profiles-qr'),
        ),
    ]
