# Generated by Django 4.2 on 2025-02-19 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='mark_as_read',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
