# Generated by Django 4.2 on 2025-03-06 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_notification_mark_as_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_reciver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_reciver', to='api.account')),
                ('message_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_sender', to='api.account')),
            ],
        ),
    ]
